server:
  port: 29998

spring:
  application:
    name: service-a

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:29999/eureka/


logging:
  level:
    root: INFO
    com.myapp: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %level - %msg%n'
