version: '3'
services:
  mysql:
    image: mysql:5.7
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sec
      MYSQL_USER: sec
      MYSQL_PASSWORD: 123456
    ports:
      - "33306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d


