server:
  port: 29992

spring:
  application:
    name: service-g

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:29999/eureka/
